### PR TITLE
Add src to rustls error, bump to 0.20.1

### PR DESCRIPTION
**Pull request by AlyoshaVasilieva**

### CODE REVIEW

**Review by jsha — APPROVED** [review]
Thanks!

**Comment by algesten** [comment]
Notice that we should not have patch version in the rustls dependency. `0.20` is correct since that will allow the end user to get .1 .2 etc on the patch level.

Never mind reverting this though since I fixed it in this branch landing next #449

**Comment by jsha** [comment]
In general that is correct, but in this case we are depending on an API that was introduced in 0.20.1, so we do need to include the patch level. Perhaps that should technically have been a semver minor release (since it introduced an API).

**Comment by algesten** [comment]
Ah got ya!

**Pull request merged**
