### PR TITLE
1.3.0

### PR DESCRIPTION
**Pull request by jsha**
To be merged after #81.

### CODE REVIEW

**Comment by lolgesten** [comment]
@jsha let's semantic version it and call it 1.3.0. it's new features! :D

**Comment by algesten** [comment]
@jsha I failed to build locally, so I made some quick fixes #90 and #91 needs to go in before publish.

**Comment by algesten** [comment]
@jsha 1.3.0 is out. 🎉 

Thank you for making so many improvements!

**Comment by jsha** [comment]
Yay! Thanks for working on those improvements with me!

**Pull request merged**
