### PR TITLE
Allow upper_case_acronyms

### PR DESCRIPTION
**Pull request by algesten**

### CODE REVIEW

**Review by jsha — APPROVED** [review]

**Comment by algesten** [comment]
Need to wait for rustc 1.51.0 on github CI.

**Comment by Berrysoft** [comment]
Any updates? It seems that the latest pull requests are blocked by this.

**Comment by jsha** [comment]
I've re-run the job to see if GitHub's CI's installed rust version has changed. Also this:

```
  = note: `-D clippy::unknown-clippy-lints` implied by `-D warnings`
```
  
Suggests we could turn something off to allow clippy to ignore the unknown lint.

**Comment by algesten** [comment]
@jsha  thanks! I agree we could turn it off for now if we want to land that lint straight away.

**Pull request merged**
