### PR TITLE
Run cargo test with minimal versions

### PR DESCRIPTION
**Pull request by jsha**
This can catch breakages that are hidden by latest version selection.

### CODE REVIEW

**Review by algesten — APPROVED** [review]
So with this we will test both for max version in the normal tests and min version?

**Comment by jsha** [comment]
Yep exactly!

**Comment by algesten** [comment]
Merge away!

**Review by algesten — COMMENTED** [review]
I think we should keep the versioning consistent.

For `rustls` we went with `>=0.20.1`, however I suspect that's not correct since I believe it will match `1.0.0`

Maybe we make the caret explicit? Or drop it in all places?

**Comment by algesten** [comment]
Let's redo this against 3.x

**Pull request closed without merging**
