### PR TITLE
Update base64 to 0.22

### PR DESCRIPTION
**Pull request by phy1729**
Also bumped rustls-pemfile in Cargo.lock to avoid duplicate dependencies.

### CODE REVIEW

**Comment by algesten** [comment]
Thanks!

**Comment by Enet4** [comment]
Hello @algesten, I noticed that this PR was supposedly already released in 2.9.7, but crates.io still lists 2.9.6 as the latest version. Any chance of having this crate version published soon?

**Comment by algesten** [comment]
lol. i forgot to `cargo publish`. i do now.

**Comment by algesten** [comment]
and done.  sorry about that!

**Pull request merged**
