### PR TITLE
Make cookies conditional

### LINKED ISSUE #16: Make 'cookie' optional
Is it possible to make the `cookie` dependency optional? When making server-to-server requests it's not often that you use cookies, and the `cookie` dependency brings in quite a few others:

```
│   ├── cookie v0.12.0
│   │   ├── time v0.1.42
│   │   │   └── libc v0.2.65 (*)
│   │   │   [dev-dependencies]
│   │   │   └── winapi v0.3.8
│   │   └── url v1.7.2
│   │       ├── idna v0.1.5
│   │       │   ├── matches v0.1.8
│   │       │   ├── unicode-bidi v0.3.4
│   │       │   │   └── matches v0.1.8 (*)
│   │       │   └── unicode-normalization v0.1.8
│   │       │       └── smallvec v0.6.10
│   │       ├── matches v0.1.8 (*)
│   │       └── percent-encoding v1.0.1
```

So, would it be acceptable to add a `cookie` feature (enabled by default perhaps) that disables this dependency?

### PR DESCRIPTION
**Pull request by orf**
Closes #16

### CODE REVIEW

**Comment by orf** [comment]
I wanted to wait for the Github actions to be merged to ensure it all worked. It seems it's still not active, any chance you could sign up for the beta here: https://github.com/features/actions ?

**Comment by algesten** [comment]
Ah ok. I signed up for the beta and enabled the CI workflow. I also added a badge to the README. Maybe if you rebase now?

**Comment by orf** [comment]
Awesome! rebased. You might want to enable this setting:

Screenshot 2019-10-20 at 19 16 53

Otherwise this is good to merge

**Comment by algesten** [comment]
That setting is already enabled :/

**Comment by orf** [comment]
Ok, awesome. So merge requests should now have a status + build indicator. I'll make a test one

**Pull request merged**
