### PR TITLE
Allow either LF or CRLF line ends for header fields

### LINKED ISSUE #321: "Header field didn't end with \r" error on some websites
On some websites, e.g. etihad.com, ureq fails with the following error:

> Header field didn't end with \r

Firefox and curl work fine.

There's 295 such websites in the top million (I'm using [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L)).

Archive with all occurrences: [ureq-header-did-not-end-well.tar.gz](https://github.com/algesten/ureq/files/5983467/ureq-header-did-not-end-well.tar.gz)

Code used for testing: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/ureq-smoke-test/src/main.rs

### PR DESCRIPTION
**Pull request by nico-abram**

### CODE REVIEW

**Review by jsha — CHANGES_REQUESTED** [review]
Welcome to the repo, @nico-abram! Thanks for finding the reference on this. Would you mind adding a test case?

**Comment by nico-abram** [comment]
Added a test case

**Review by jsha — APPROVED** [review]
Thanks!

**Comment by algesten** [comment]
Being lenient seems good. Thanks!

**Pull request merged**
