### PR TITLE
Add flate2 and automatic decompression

### PR DESCRIPTION
**Pull request by adrianN**
I want to work on issue #29, mostly to learn some Rust. I added literally ten lines that, to me, look like they should add support for automatic decompression. I open this PR before writing any tests to get a discussion started whether I'm even working on the right file. I only have little time per week on this, so if you want to get it done quickly, somebody else should work on this.

### CODE REVIEW

**Comment by algesten** [comment]
Hi @adrianN thanks for the PR! 

My main excitement is currently for the `future` branch, where I did a complete rewrite, including gzip support.

Having said that, I'm not that attached to the main branch code, so if you want to make it support deflate (and maybe gzip, since flate2 has both?) as a learning opportunity, go ahead!

You're in the right files!

**Comment by jsha** [comment]
@algesten It looks like the `future` branch adds async support, but the main branch says "Blocking forever." I'm guessing sometime between the last comment and today you split out the rewrite you were working on into https://github.com/algesten/hreq. Is that right?

@adrianN is this branch ready for review? It looks has accumulated some merge conflicts.

**Comment by algesten** [comment]
@jsha  correct! the future branch can be deleted. nothing of interest there.

**Comment by algesten** [comment]
The default branch is now "main". Closing this PR to not accidentally merge to the defunct "master".

**Pull request closed without merging**
