### PR TITLE
Don't reuse conns with bytes pending from server

### PR DESCRIPTION
**Pull request by jsha**
Related to #361 and #124.

### CODE REVIEW

**Review by algesten — APPROVED** [review]
This looks exactly right.

**Review by algesten — APPROVED** [review]
Let's land a publish a new version. Thanks!

**Comment by algesten** [comment]
@jsha I was thinking a bit more about this, and wonder if we have covered all the cases. While this check will cover a lot of cases, I wonder if there isn't a race condition here also. Consider:

1. ureq does this check, all looks good, connection still open.
2. remote closes the connection.
3. ureq sends next request.

Given distributed systems, we can't really know whether a connection can be reused until we sent the next request successfully.

**Comment by jsha** [comment]
There's definitely a race condition, and the [HTTP RFC talks about it](https://tools.ietf.org/html/rfc7230#section-6.3.1):

>   Connections can be closed at any time, with or without intention.
>   Implementations ought to anticipate the need to recover from
>   asynchronous close events.

>    When an inbound connection is closed prematurely, a client MAY open a
   new connection and automatically retransmit an aborted sequence of
   requests if all of those requests have idempotent methods (Section
   4.2.2 of [RFC7231]).  A proxy MUST NOT automatically retry
   non-idempotent requests.

>   A user agent MUST NOT automatically retry a request with a non-
   idempotent method unless it has some means to know that the request
   semantics are actually idempotent, regardless of the method, or some
   means to detect that the original request was never applied.
   
So: connections can be closed at any time, and the remedy is retrying. But retrying doesn't work if you've sent a POST request, because they are not idempotent. So it's best to try and reduce the likelihood of sending on a closed connection as much as possible.

One thing that's not clear to me is whether it's permissible to retry an incompletely sent POST. For instance, if you sent only the headers, or sent (Content-Length - 1) bytes, then discovered the connection was closed, could you assume the POST was not applied and retry automatically?

**Comment by algesten** [comment]
@jsha 

> One thing that's not clear to me is whether it's permissible to retry an incompletely sent POST.

I think this line in the spec:

>> or some means to detect that the original request was never applied.

means it's not permissible. We can't know the reason for the connection closing. Could be the server, or some middle box. The server might have applied  the non-idempotent request.

**Comment by DoumanAsh** [comment]
The only extra you can do is to flush after sending headers, making sure server receives it triggering whatever other reason which would lead server to close connection I think (which also helped us to mitigate this situation)

**Pull request merged**
